// Code generated by "stringer -type Linkage"; DO NOT EDIT.

package cc

import "strconv"

const _Linkage_name = "NoneInternalExternal"

var _Linkage_index = [...]uint8{0, 4, 12, 20}

func (i Linkage) String() string {
	if i < 0 || i >= Linkage(len(_Linkage_index)-1) {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}
