// Code generated by "stringer -type Namespace"; DO NOT EDIT.

package cc

import "strconv"

const _Namespace_name = "NSIdentifiersNSTags"

var _Namespace_index = [...]uint8{0, 13, 19}

func (i Namespace) String() string {
	if i < 0 || i >= Namespace(len(_Namespace_index)-1) {
		return "Namespace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Namespace_name[_Namespace_index[i]:_Namespace_index[i+1]]
}
